# Generated by Django 4.1.6 on 2023-04-09 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0008_alter_history_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 9, 8, 31, 48, 918328, tzinfo=datetime.timezone.utc)),
        ),
    ]
